# Generated by Django 3.0.4 on 2020-04-02 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='track',
        ),
    ]
