# Generated by Django 3.0.4 on 2020-04-02 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_like_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='title',
        ),
        migrations.AddField(
            model_name='like',
            name='track',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='tracks.Track'),
            preserve_default=False,
        ),
    ]
