# Generated by Django 3.0.4 on 2020-04-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0006_auto_20200402_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
